version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: echo "$CIRCLE_BUILD_NUM again"
  dockerize:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=0.0.$CIRCLE_BUILD_NUM
          docker build -t volentixlabs/circlecidemo:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push volentixlabs/circlecidemo:$TAG
  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt install python-pip python-dev
      - run: sudo pip install awscli
      - run: sudo aws --version
workflows:
  version: 2
  build_and_dockerize:
    jobs:
      - deploy