version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: echo "$CIRCLE_BUILD_NUM again"
  dockerize:
    machine: true
    steps:
      - checkout
      - run: |
          TAG=v0.0.$CIRCLE_BUILD_NUM
          docker build -t volentixlabs/circlecidemo:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push volentixlabs/circlecidemo:$TAG
  deploy:
    docker:
      - image: volentixlabs/aws-kube-deploy:v0.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: aws --version
      - run: kops export kubecfg
      - run: |
          TAG=v0.0.$CIRCLE_PREVIOUS_BUILD_NUM
          sed 's/BUILD_VERSION/'$TAG'/' kube/dev.yml.template > kube/dev.yml
          kubectl apply -f kube/dev.yml
workflows:
  version: 2
  build_and_dockerize:
    jobs:
      - build
      - dockerize:
          requires:
            - build
      - deploy:
          requires:
            - dockerize